# Site wide configuration

title:            Technology Drifts
locale:           en_US
url:		https://sivansasidharan.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
    
remote_theme:jekyll-theme-cayman

# Site owner
owner:
  name: Sivan Sasidharan
  avatar: mine.jpg
  bio: "A consultant technologist with experience in delivering business values by enabling focus, innovation, quality services at top class organizations.
Interested in driving & aligning BigData strategy for large enterprises; identifying optimized architecture & choice of best fit technology."
  email: sivan.consult@gmail.com
  disqus-shortname: me-sivansasidharan
  twitter: sivansasidharan
  facebook: sivansasidharan
  google:
   plus: #username
  analytics:
  verify:
  ad-client:
  ad-slot:
  bing-verify:
  github: sivansasidharan
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sivansasidharan
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
